const express = require('express');
const bodyParser = require('body-parser');
const axios = require('axios');
const fs = require('fs');
const { google } = require('googleapis');
const app = express();
app.use(bodyParser.json());
const VERIFY_TOKEN = "bizmapia_verify_2024";
const TOKEN = process.env.WHATSAPP_TOKEN;
const PHONE_NUMBER_ID = process.env.PHONE_NUMBER_ID;
const PORT = process.env.PORT || 10000;
const SHEET_ID = process.env.GOOGLE_SHEET_ID || process.env.SHEET_ID || "1MnPTAMafVTuSX2uQKCpP6GKKadQBLXfrgnySigY8cHY";
const CONTACT_NUMBER = "8590175977";
const EMAIL_ID = "bizmapia.com@gmail.com";
const WEBSITE = "www.bizmapia.com";
const WPBS_PAYMENT_LINK = "https://rzp.io/rzp/WxKS0dZ";
const WPBS_AMOUNT = "₹2,500";
console.log("========== GOD MODE + WPBS 3Q V4 EXPLAINED COMPARISON + SMART RESUME FIX ==========");
let pendingChatsMemory = {};
try{ if(fs.existsSync("/tmp/pending_chats.json")){ pendingChatsMemory = JSON.parse(fs.readFileSync("/tmp/pending_chats.json")); console.log("Loaded pending chats:", Object.keys(pendingChatsMemory).length); } }catch(e){ pendingChatsMemory = {}; }
async function getSheetsClient(){try{let creds=process.env.GOOGLE_CREDENTIALS;if(!creds)return null;let credentials=JSON.parse(creds);if(credentials.private_key)credentials.private_key=credentials.private_key.replace(/\\n/g,'\n');const auth=new google.auth.GoogleAuth({credentials,scopes:['https://www.googleapis.com/auth/spreadsheets']});return google.sheets({version:'v4',auth});}catch(e){return null;}}
async function appendToSheet(row){try{const sheets=await getSheetsClient();if(!sheets||!SHEET_ID)return;let finalRow=row.slice(0,9);await sheets.spreadsheets.values.append({spreadsheetId:SHEET_ID,range:'Sheet1!A:I',valueInputOption:'USER_ENTERED',requestBody:{values:[finalRow]}});}catch(e){}}
async function logAllChat(phone,type,status,lang,stage,extra=''){try{const dateStr=new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});const details=`${stage} | ${type} | ${status} | ${extra}`.substring(0,200);const langInfo=`${lang} | ${status} | ${stage}`;const row=[dateStr,phone,type,details,'',phone,'',stage,langInfo];const sheets=await getSheetsClient();if(!sheets||!SHEET_ID)return;await sheets.spreadsheets.values.append({spreadsheetId:SHEET_ID,range:'Sheet1!A:I',valueInputOption:'USER_ENTERED',requestBody:{values:[row]}});}catch(e){}}
const ASSETS={posters:{welcome:"https://files.catbox.moe/zmj6te.jpg",customer:"https://files.catbox.moe/nbjslu.jpg",driver:"https://files.catbox.moe/2trzp7.jpg",business:"https://files.catbox.moe/sylcqa.jpg",opportunity:"https://files.catbox.moe/y8m3lq.jpg",selectOption:"https://files.catbox.moe/pw2zi4.png",freeRecharge:"https://files.catbox.moe/c03g3q.jpg",businessBenefit:"https://files.catbox.moe/8ayus6.jpg",franchiseBrochure:"https://files.catbox.moe/FRANCHISEE-NEW-BIZMAPIA.jpg",businessBrochure:"https://files.catbox.moe/BUSINESS-NEW-BIZMAPIA.jpg",wpbs:"https://files.catbox.moe/pw2zi4.png"},apps:{customer:"https://play.google.com/store/apps/details?id=com.panditprogrammer.bizmapia",driver:"https://play.google.com/store/apps/details?id=com.panditprogrammer.bizmapia_driver"},videos:{main_opp:"https://youtu.be/8ZnDlvbgG_c?si=a5ONBZg6Oe8WuGTP",opp_1:"https://youtu.be/_y2JeFHBnqg?si=igKYEPjGheuARuZe",opp_2:"https://youtu.be/GqolfqgHiCU?si=ySBbc_qLD2mLyBmN",opp_3:"https://youtu.be/GqolfqgHiCU?si=qTxRIIeq7iP5X5Jh",opp_4:"https://youtu.be/r0X77XfmF94?si=XdbPE4Ml2_jkv8zW",opp_5:"https://youtu.be/r0X77XfmF94?si=XdbPE4Ml2_jkv8zW"}};
const LANG_TEXT={EN:{whatToKnow:"What would you like to know?",selectMenu:"Please select from menu below 👇",hiAgain:"👉 Type *HI* to Start Again 🙏",customerH:"🚕 *CUSTOMER - Book a Taxi & Services*",driverH:"🚕 *DRIVER PARTNER - Attach Your Vehicle & Start Earning!*",businessH:"🏪 *BUSINESS OWNER - List Your Business & Get Customers*",oppH:"💼 *FRANCHISE OPPORTUNITY - Own a Franchise in Your Area*",oppSub:"4 Business Opportunities Under One Brand",formName:"*Name :-*\nEnter your full name:",formContact:"*Contact number :-*\nEnter mobile number:",formPlace:"*Place :-*\nEnter place / city:",formOcc:"*Current occupation :-*\nSelect:",yesNoQ:"You want to grab this opportunity?",thanksEnq:"✅ Thank you",team24:"Our team will contact within 24h 🙏"},HI:{whatToKnow:"आप क्या जानना चाहते हैं?",selectMenu:"कृपया नीचे दिए गए मेनू से चुनें 👇",hiAgain:"👉 फिर से शुरू करने के लिए *HI* टाइप करें 🙏",customerH:"🚕 *कस्टमर - टैक्सी और सर्विस बुक करें*",driverH:"🚕 *ड्राइवर पार्टनर - अपनी गाड़ी जोड़ें और कमाना शुरू करें!*",businessH:"🏪 *बिजनेस ओनर - अपना बिजनेस लिस्ट करें और ग्राहक पाएं*",oppH:"💼 *फ्रेंचाइजी अवसर - अपने क्षेत्र में फ्रेंचाइजी लें*",oppSub:"एक ब्रांड के तहत 4 बिजनेस अवसर",formName:"*नाम :-*\nअपना पूरा नाम लिखें:",formContact:"*मोबाइल नंबर :-*\nअपना नंबर लिखें:",formPlace:"*जगह :-*\nअपना शहर लिखें:",formOcc:"*वर्तमान व्यवसाय :-*\nचुनें:",yesNoQ:"क्या आप यह अवसर लेना चाहते हैं?",thanksEnq:"✅ धन्यवाद",team24:"हमारी टीम 24 घंटे में संपर्क करेगी 🙏"},ML:{whatToKnow:"നിങ്ങൾ എന്താണ് അറിയാൻ ആഗ്രഹിക്കുന്നത്?",selectMenu:"ദയവായി താഴെയുള്ള മെനുവിൽ നിന്ന് തിരഞ്ഞെടുക്കുക 👇",hiAgain:"👉 വീണ്ടും ആരംഭിക്കാൻ *HI* ടൈപ്പ് ചെയ്യുക 🙏",customerH:"🚕 *കസ്റ്റമർ - ടാക്സി & സർവീസുകൾ ബുക്ക് ചെയ്യുക*",driverH:"🚕 *ഡ്രൈവർ പാർട്ണർ - വാഹനം അറ്റാച്ച് ചെയ്ത് വരുമാനം നേടൂ!*",businessH:"🏪 *ബിസിനസ് ഓണർ - ബിസിനസ് ലിസ്റ്റ് ചെയ്ത് കസ്റ്റമേഴ്സിനെ നേടൂ*",oppH:"💼 *ഫ്രാഞ്ചൈസി അവസരം - ഏരിയയിൽ ഫ്രാഞ്ചൈസി സ്വന്തമാക്കൂ*",oppSub:"ഒരു ബ്രാൻഡിന് കീഴിൽ 4 ബിസിനസ് അവസരങ്ങൾ",formName:"*പേര് :-*\nനിങ്ങളുടെ പേര് നൽകുക:",formContact:"*ഫോൺ നമ്പർ :-*\nനമ്പർ നൽകുക:",formPlace:"*സ്ഥലം :-*\nനിങ്ങളുടെ സ്ഥലം നൽകുക:",formOcc:"*ജോലി :-*\nതിരഞ്ഞെടുക്കുക:",yesNoQ:"ഈ അവസരം സ്വന്തമാക്കാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?",thanksEnq:"✅ നന്ദി",team24:"ടീം 24 മണിക്കൂറിനുള്ളിൽ ബന്ധപ്പെടും 🙏"}};
const getT=(lang,key)=>(LANG_TEXT[lang]&&LANG_TEXT[lang][key])||LANG_TEXT.EN[key];
const sessions={};const oppTimers={};const processedIds=new Set();
function getSession(p){if(!sessions[p])sessions[p]={lang:"EN",stage:"NEW",lastOpp:"",form:{}};return sessions[p];}
async function sendText(to,body){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"text",text:{body}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){console.log("sendText fail",e.message);}}
async function sendImage(to,link,caption){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"image",image:{link,caption}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){console.log("sendImage fail, sending text fallback");await sendText(to,caption);}}
async function sendButtons(to,body,buttons){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"interactive",interactive:{type:"button",body:{text:body},action:{buttons:buttons.map(b=>({type:"reply",reply:{id:b.id,title:b.title.substring(0,20)}}))}}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){await sendText(to,body);}}
async function sendList(to,body,buttonText,sections){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"interactive",interactive:{type:"list",body:{text:body},action:{button:buttonText,sections}}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){await sendText(to,body);}}
async function sendWelcomeTextAndLanguage(to){const welcomeText=`👋 *Welcome to Bizmapia! Your Success, Our Platform* 🙏\n\nThank you for reaching out to us!\n\nPlease select your language / भाषा चुनें / ഭാഷ തിരഞ്ഞെടുക്കുക 👇`;await sendButtons(to,welcomeText,[{id:"lang_en",title:"English"},{id:"lang_hi",title:"Hindi"},{id:"lang_ml",title:"Malayalam"}]);}
function loadReminders(){try{if(fs.existsSync("/tmp/reminders.json"))return JSON.parse(fs.readFileSync("/tmp/reminders.json"));}catch(e){}return [];}
function saveReminders(list){try{fs.writeFileSync("/tmp/reminders.json",JSON.stringify(list));}catch(e){}}
function addReminder(phone,type){const list=loadReminders();list.push({phone,type,claimedAt:Date.now(),sent1h:false,sent24h:false,sent48h:false,sent72h:false});saveReminders(list);}
async function checkReminders(){let list=loadReminders();let changed=false;const now=Date.now();for(let r of list){const diffH=(now-r.claimedAt)/(1000*60*60);if(!r.sent1h&&diffH>=1){await sendImage(r.phone,ASSETS.posters.freeRecharge,`⏰ *Your free recharge going to expire*\n\n33 Rupees Recharge - 24hr Unlimited Trips\nActivate now:\n${ASSETS.apps.driver}`);r.sent1h=true;changed=true;}if(!r.sent24h&&diffH>=24){await sendText(r.phone,`🔔 *Re-activate discount*\nYour FREE recharge pending:\n${ASSETS.apps.driver}`);r.sent24h=true;changed=true;}if(!r.sent48h&&diffH>=48){await sendText(r.phone,`💬 *Need help to verify?*\nTeam can help:\n${ASSETS.apps.driver}`);r.sent48h=true;changed=true;}if(!r.sent72h&&diffH>=72){await sendText(r.phone,`😔 *Free recharge expired*\nStill join:\n${ASSETS.apps.driver}`);r.sent72h=true;changed=true;}}if(changed)saveReminders(list.filter(r=>!r.sent72h));}
setInterval(checkReminders,5*60*1000);
let pendingChats=pendingChatsMemory;
function setPendingChat(phone,lang,stageName){if(!pendingChats[phone])pendingChats[phone]={lang:lang||"EN",stage:stageName,lastActivity:Date.now(),reminders:{r1:false,r2:false,r3:false}};else{pendingChats[phone].lang=lang||pendingChats[phone].lang;pendingChats[phone].stage=stageName;pendingChats[phone].lastActivity=Date.now();}try{fs.writeFileSync("/tmp/pending_chats.json",JSON.stringify(pendingChats));}catch(e){}}
function clearPendingChat(phone){if(pendingChats[phone]){delete pendingChats[phone];try{fs.writeFileSync("/tmp/pending_chats.json",JSON.stringify(pendingChats));}catch(e){}}}
function getStageDisplayName(stage){const map={"LANG_SELECTION":"Language Selection","AD_SELECTION":"Ad Selection (WPBS / Business Opportunity)","WPBS_Q1_MSG":"WPBS Q1 - Messages per month","WPBS_Q2_NUMBERS":"WPBS Q2 - Number of WhatsApp Numbers","WPBS_Q3_ADS":"WPBS Q3 - Number of Ads","WPBS_RECOMMENDED":"WPBS Recommended Plan & Payment","WPBS_PAYMENT":"WPBS Payment - Pay 2500 Advance","FORM_NAME":"Franchise Form - Name","FORM_CONTACT":"Franchise Form - Contact Number","FORM_PLACE":"Franchise Form - Place","FORM_OCCUPATION":"Franchise Form - Occupation","CUSTOMER_VIEWED":"Customer App","DRIVER_VIEWED":"Driver App","BUSINESS_VIEWED":"Business Listing","MAIN_MENU":"Main Menu"};if(stage.startsWith("OPP_"))return stage.replace("OPP_","").replace("_VIEWED","").replace("opp_","Franchise ");return map[stage]||stage;}
async function sendResumeForStage(phone, stage, lang){
  const stageName = getStageDisplayName(stage);
  if(stage==="WPBS_Q1_MSG"){await sendText(phone,`👋 *Hi! You left your WPBS enquiry incomplete.*\n\n⚠️ You have not completed *${stageName}* - Go back and complete your application now!\n\n👉 Reply *HI* to continue or select below:`);await sendButtons(phone,"Q1/3: Messages per month? - Complete now:",[{id:"wpbs_q1_l1", title:"Upto 1000"},{id:"wpbs_q1_l2", title:"1000-5000"},{id:"wpbs_q1_l3", title:"Above 5000"}]);}
  else if(stage==="WPBS_Q2_NUMBERS"){await sendText(phone,`👋 *Hi! You left your WPBS enquiry incomplete.*\n\n⚠️ You have not completed *${stageName}* - Go back and complete your application now!`);await sendButtons(phone,"Q2/3: How many WhatsApp Numbers? - Complete now:",[{id:"wpbs_q2_l1", title:"1 Number"},{id:"wpbs_q2_l2", title:"2 to 5"},{id:"wpbs_q2_l3", title:"More than 5"}]);}
  else if(stage==="WPBS_Q3_ADS"){await sendText(phone,`👋 *Hi! You left your WPBS enquiry incomplete.*\n\n⚠️ You have not completed *${stageName}* - Go back and complete your application now!`);await sendButtons(phone,"Q3/3: How many Ads? - Complete now:",[{id:"wpbs_q3_l1", title:"1 Ad"},{id:"wpbs_q3_l2", title:"2 to 5 Ads"},{id:"wpbs_q3_l3", title:"More than 5 Ads"}]);}
  else if(stage==="WPBS_RECOMMENDED"){await sendText(phone,`👋 *Hi! You left your WPBS enquiry incomplete.*\n\n⚠️ You have not completed *${stageName}* - You have not locked your plan yet!\n\nGo back and complete your application now - Pay ₹2500 to lock!`);await sendButtons(phone,"Complete your WPBS payment:",[{id:"wpbs_restart", title:"View My Plan"},{id:"menu", title:"Main Menu"}]);}
  else if(stage==="WPBS_PAYMENT"){await sendText(phone,`👋 *Hi! You left your WPBS payment incomplete.*\n\n⚠️ You have not completed *Payment - Pay ₹2500* - Go back and complete your application now!\n\nPay here: ${WPBS_PAYMENT_LINK}`);await sendButtons(phone,"Complete payment:",[{id:"wpbs_paid", title:"I Paid - Confirm"},{id:"menu", title:"Main Menu"}]);}
  else {await sendText(phone,`👋 *Hi! You left your Bizmapia chat incomplete.*\n\n⚠️ You were at *${stageName}* - You have not completed it.\n\nGo back and complete your application now!\n👉 Reply *HI* to continue\n📞 ${CONTACT_NUMBER}`);const rows=getMainMenuRows(lang);setTimeout(async()=>{await sendList(phone,`You were at ${stageName} - Resume:`, "Resume Menu",[{title:"Menu",rows}]);},1000);}
}
async function checkPendingChats(){
  const now=Date.now();let changed=false;console.log(`[REMINDER CHECK] Checking ${Object.keys(pendingChats).length} pending`);for(let phone in pendingChats){const p=pendingChats[phone];const diffMin=(now-p.lastActivity)/(1000*60);const stageDisplay=getStageDisplayName(p.stage);console.log(`[REMINDER] ${phone} at ${p.stage} for ${Math.floor(diffMin)} min`);if(!p.reminders.r1&&diffMin>=10){await sendText(phone,`🔔 *Reminder 1 - Incomplete Application*\n\n👋 Hi! You left your Bizmapia chat incomplete.\nYou were at *${stageDisplay}* - Complete in 1 min!\n👉 Reply *HI* to continue and complete *${stageDisplay}* now!\n📞 ${CONTACT_NUMBER}`);await logAllChat(phone,'AUTO_REMINDER','REMINDER_10MIN_SENT',p.lang,p.stage,`10min - ${stageDisplay}`);setTimeout(async()=>{await sendResumeForStage(phone,p.stage,p.lang);},3000);p.reminders.r1=true;changed=true;}else if(!p.reminders.r2&&diffMin>=30){await sendText(phone,`⏰ *Reminder 2 - Still Pending: ${stageDisplay}*\n\n⚠️ You have not completed *${stageDisplay}* - Go back and complete your application now!\n👉 Reply *HI*`);await logAllChat(phone,'AUTO_REMINDER','REMINDER_30MIN_SENT',p.lang,p.stage,`30min - ${stageDisplay}`);setTimeout(async()=>{await sendResumeForStage(phone,p.stage,p.lang);},2000);p.reminders.r2=true;changed=true;}else if(!p.reminders.r3&&diffMin>=1440){await sendImage(phone,ASSETS.posters.opportunity,`🔔 *Last Chance - Incomplete: ${stageDisplay}*\n\nYou have not completed *${stageDisplay}*\nGo back and complete your application now!\n👉 Reply *HI* to continue`);await logAllChat(phone,'AUTO_REMINDER','REMINDER_24H_SENT',p.lang,p.stage,`24h - ${stageDisplay}`);setTimeout(async()=>{await sendResumeForStage(phone,p.stage,p.lang);},2000);p.reminders.r3=true;changed=true;}}for(let phone in pendingChats){if((now-pendingChats[phone].lastActivity)>72*60*60*1000&&pendingChats[phone].reminders.r3){delete pendingChats[phone];changed=true;}}if(changed)try{fs.writeFileSync("/tmp/pending_chats.json",JSON.stringify(pendingChats));}catch(e){}}
setInterval(checkPendingChats,2*60*1000);
