const express=require('express');const bodyParser=require('body-parser');const axios=require('axios');const fs=require('fs');const {google}=require('googleapis');const app=express();app.use(bodyParser.json());
const VERIFY_TOKEN=process.env.VERIFY_TOKEN||"bizmapia_verify_2024";
const TOKEN=process.env.WHATSAPP_TOKEN;const PHONE_NUMBER_ID=process.env.PHONE_NUMBER_ID;const PORT=process.env.PORT||10000;
const SHEET_ID=process.env.GOOGLE_SHEET_ID||process.env.SHEET_ID||"1MnPTAMafVTuSX2uQKCpP6GKKadQBLXfrgnySigY8cHY";
const CONTACT_NUMBER="8590175977";const EMAIL_ID="bizmapia.com@gmail.com";const WEBSITE="www.bizmapia.com";
const WPBS_PAYMENT_LINK="https://rzp.io/rzp/WxKS0dZ";const WPBS_AMOUNT="₹2,500";
console.log("========== V4.7 FINAL - POSTER+PAYNOW+RESTART TOGETHER L1 L2 L3 + I PAID REMINDER ==========");
let pendingChatsMemory={};try{if(fs.existsSync("/tmp/pending_chats.json")){pendingChatsMemory=JSON.parse(fs.readFileSync("/tmp/pending_chats.json"));}}catch(e){pendingChatsMemory={};}
async function getSheetsClient(){try{let creds=process.env.GOOGLE_CREDENTIALS;if(!creds)return null;let credentials=JSON.parse(creds);if(credentials.private_key)credentials.private_key=credentials.private_key.replace(/\\n/g,'\n');const auth=new google.auth.GoogleAuth({credentials,scopes:['https://www.googleapis.com/auth/spreadsheets']});return google.sheets({version:'v4',auth});}catch(e){return null;}}
async function appendToSheet(row){try{const sheets=await getSheetsClient();if(!sheets||!SHEET_ID)return;await sheets.spreadsheets.values.append({spreadsheetId:SHEET_ID,range:'Sheet1!A:I',valueInputOption:'USER_ENTERED',requestBody:{values:[row.slice(0,9)]}});}catch(e){}}
async function logAllChat(phone,type,status,lang,stage,extra=''){try{const dateStr=new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});const details=`${stage} | ${type} | ${status} | ${extra}`.substring(0,200);const row=[dateStr,phone,type,details,'',phone,'',stage,`${lang} | ${status} | ${stage}`];const sheets=await getSheetsClient();if(!sheets||!SHEET_ID)return;await sheets.spreadsheets.values.append({spreadsheetId:SHEET_ID,range:'Sheet1!A:I',valueInputOption:'USER_ENTERED',requestBody:{values:[row]}});}catch(e){}}
const ASSETS={posters:{welcome:"https://files.catbox.moe/zmj6te.jpg",customer:"https://files.catbox.moe/nbjslu.jpg",driver:"https://files.catbox.moe/2trzp7.jpg",business:"https://files.catbox.moe/sylcqa.jpg",opportunity:"https://files.catbox.moe/y8m3lq.jpg",selectOption:"https://files.catbox.moe/zmj6te.jpg",freeRecharge:"https://files.catbox.moe/c03g3q.jpg",businessBenefit:"https://files.catbox.moe/8ayus6.jpg",franchiseBrochure:"https://files.catbox.moe/FRANCHISEE-NEW-BIZMAPIA.jpg",businessBrochure:"https://files.catbox.moe/BUSINESS-NEW-BIZMAPIA.jpg",wpbs:"https://files.catbox.moe/pw2zi4.png",wpbs_l1:"https://files.catbox.moe/gfev45.png",wpbs_higher:"https://files.catbox.moe/7y1s27.png"},apps:{customer:"https://play.google.com/store/apps/details?id=com.panditprogrammer.bizmapia",driver:"https://play.google.com/store/apps/details?id=com.panditprogrammer.bizmapia_driver"},videos:{main_opp:"https://youtu.be/8ZnDlvbgG_c",opp_1:"https://youtu.be/_y2JeFHBnqg",opp_2:"https://youtu.be/GqolfqgHiCU",opp_3:"https://youtu.be/GqolfqgHiCU",opp_4:"https://youtu.be/r0X77XfmF94",opp_5:"https://youtu.be/r0X77XfmF94"}};
const LANG_TEXT={
EN:{whatToKnow:"What would you like to know?",selectMenu:"Please select from menu below 👇",hiAgain:"👉 Type *HI* to Start Again 🙏",customerH:"🚕 *CUSTOMER - Book a Taxi & Services*",driverH:"🚕 *DRIVER PARTNER - Attach Your Vehicle & Start Earning!*",businessH:"🏪 *BUSINESS OWNER - List Your Business & Get Customers*",oppH:"💼 *FRANCHISE OPPORTUNITY - Own a Franchise in Your Area*",oppSub:"4 Business Opportunities Under One Brand",formName:"*Name :-*\nEnter your full name:",formContact:"*Contact number :-*\nEnter mobile number:",formPlace:"*Place :-*\nEnter place / city:",formOcc:"*Current occupation :-*\nSelect:",yesNoQ:"You want to grab this opportunity?",thanksEnq:"✅ Thank you",team24:"Our team will contact within 24h 🙏"},
HI:{whatToKnow:"आप क्या जानना चाहते हैं?",selectMenu:"कृपया नीचे दिए गए मेनू से चुनें 👇",hiAgain:"👉 फिर से शुरू करने के लिए *HI* टाइप करें 🙏",customerH:"🚕 *कस्टमर - टैक्सी और सर्विस बुक करें*",driverH:"🚕 *ड्राइवर पार्टनर - अपनी गाड़ी जोड़ें और कमाना शुरू करें!*",businessH:"🏪 *बिजनेस ओनर - अपना बिजनेस लिस्ट करें और ग्राहक पाएं*",oppH:"💼 *फ्रेंचाइजी अवसर - अपने क्षेत्र में फ्रेंचाइजी लें*",oppSub:"एक ब्रांड के तहत 4 बिजनेस अवसर",formName:"*नाम :-*\nअपना पूरा नाम लिखें:",formContact:"*मोबाइल नंबर :-*\nअपना नंबर लिखें:",formPlace:"*जगह :-*\nअपना शहर लिखें:",formOcc:"*वर्तमान व्यवसाय :-*\nचुनें:",yesNoQ:"क्या आप यह अवसर लेना चाहते हैं?",thanksEnq:"✅ धन्यवाद",team24:"हमारी टीम 24 घंटे में संपर्क करेगी 🙏"},
ML:{whatToKnow:"നിങ്ങൾ എന്താണ് അറിയാൻ ആഗ്രഹിക്കുന്നത്?",selectMenu:"ദയവായി താഴെയുള്ള മെനുവിൽ നിന്ന് തിരഞ്ഞെടുക്കുക 👇",hiAgain:"👉 വീണ്ടും ആരംഭിക്കാൻ *HI* ടൈപ്പ് ചെയ്യുക 🙏",customerH:"🚕 *കസ്റ്റമർ - ടാക്സി & സർവീസുകൾ ബുക്ക് ചെയ്യുക*",driverH:"🚕 *ഡ്രൈവർ പാർട്ണർ - വാഹനം അറ്റാച്ച് ചെയ്ത് വരുമാനം നേടൂ!*",businessH:"🏪 *ബിസിനസ് ഓണർ - ബിസിനസ് ലിസ്റ്റ് ചെയ്ത് കസ്റ്റമേഴ്സിനെ നേടൂ*",oppH:"💼 *ഫ്രാഞ്ചൈസി അവസരം - ഏരിയയിൽ ഫ്രാഞ്ചൈസി സ്വന്തമാക്കൂ*",oppSub:"ഒരു ബ്രാൻഡിന് കീഴിൽ 4 ബിസിനസ് അവസരങ്ങൾ",formName:"*പേര് :-*\nനിങ്ങളുടെ പേര് നൽകുക:",formContact:"*ഫോൺ നമ്പർ :-*\nനമ്പർ നൽകുക:",formPlace:"*സ്ഥലം :-*\nനിങ്ങളുടെ സ്ഥലം നൽകുക:",formOcc:"*ജോലി :-*\nതിരഞ്ഞെടുക്കുക:",yesNoQ:"ഈ അവസരം സ്വന്തമാക്കാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?",thanksEnq:"✅ നന്ദി",team24:"ടീം 24 മണിക്കൂറിനുള്ളിൽ ബന്ധപ്പെടും 🙏"}
};
const getT=(l,k)=>(LANG_TEXT[l]&&LANG_TEXT[l][k])||LANG_TEXT.EN[k];const sessions={};const oppTimers={};const processedIds=new Set();function getSession(p){if(!sessions[p])sessions[p]={lang:"EN",stage:"NEW",lastOpp:"",form:{}};return sessions[p];}
async function sendText(to,body){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"text",text:{body}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){}}
async function sendImage(to,link,caption){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"image",image:{link,caption}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){await sendText(to,caption);}}
async function sendButtons(to,body,buttons){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"interactive",interactive:{type:"button",body:{text:body},action:{buttons:buttons.map(b=>({type:"reply",reply:{id:b.id,title:b.title.substring(0,20)}}))}}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){await sendText(to,body);}}
async function sendPayNowUrlButton(to,body,payUrl){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"interactive",interactive:{type:"cta_url",body:{text:body},action:{name:"cta_url",parameters:{display_text:"Pay Now ₹2500",url:payUrl}}}},{headers:{Authorization:`Bearer ${TOKEN}`}});return true;}catch(e){console.log("CTA URL failed, fallback:",e.response?.data||e.message);await sendText(to,body+`\n\n💳 Pay Now: ${payUrl}`);return false;}}
async function sendList(to,body,buttonText,sections){try{await axios.post(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`,{messaging_product:"whatsapp",to,type:"interactive",interactive:{type:"list",body:{text:body},action:{button:buttonText,sections}}},{headers:{Authorization:`Bearer ${TOKEN}`}});}catch(e){await sendText(to,body);}}
async function sendWelcomeTextAndLanguage(to){await sendButtons(to,"👋 *Welcome to Bizmapia! Your Success, Our Platform* 🙏\n\nThank you for reaching out!\n\nPlease select your language / भाषा चुनें / ഭാഷ തിരഞ്ഞെടുക്കുക 👇",[{id:"lang_en",title:"English"},{id:"lang_hi",title:"Hindi"},{id:"lang_ml",title:"Malayalam"}]);}
function loadReminders(){try{if(fs.existsSync("/tmp/reminders.json"))return JSON.parse(fs.readFileSync("/tmp/reminders.json"));}catch(e){}return [];}
function saveReminders(list){try{fs.writeFileSync("/tmp/reminders.json",JSON.stringify(list));}catch(e){}}
function addReminder(phone,type){const list=loadReminders();list.push({phone,type,claimedAt:Date.now(),sent1h:false,sent24h:false,sent48h:false,sent72h:false});saveReminders(list);}
async function checkReminders(){let list=loadReminders();let changed=false;const now=Date.now();for(let r of list){const diffH=(now-r.claimedAt)/(1000*60*60);if(!r.sent1h&&diffH>=1){await sendImage(r.phone,ASSETS.posters.freeRecharge,`⏰ *Your free recharge going to expire*\n${ASSETS.apps.driver}`);r.sent1h=true;changed=true;}}if(changed)saveReminders(list.filter(r=>!r.sent72h));}
setInterval(checkReminders,5*60*1000);
let pendingChats=pendingChatsMemory;
function setPendingChat(phone,lang,stageName){if(!pendingChats[phone])pendingChats[phone]={lang:lang||"EN",stage:stageName,lastActivity:Date.now(),reminders:{r1:false,r2:false,r3:false}};else{pendingChats[phone].lang=lang||pendingChats[phone].lang;pendingChats[phone].stage=stageName;pendingChats[phone].lastActivity=Date.now();}try{fs.writeFileSync("/tmp/pending_chats.json",JSON.stringify(pendingChats));}catch(e){}}
function clearPendingChat(phone){if(pendingChats[phone]){delete pendingChats[phone];try{fs.writeFileSync("/tmp/pending_chats.json",JSON.stringify(pendingChats));}catch(e){}}}
function getStageDisplayName(stage){const map={"LANG_SELECTION":"Language Selection","AD_SELECTION":"Ad Selection","WPBS_Q1_MSG":"WPBS Q1 - Messages per month","WPBS_Q2_NUMBERS":"WPBS Q2 - Number of WhatsApp Numbers","WPBS_Q3_ADS":"WPBS Q3 - Number of Ads","WPBS_RECOMMENDED":"WPBS Recommended Plan","WPBS_PAYMENT":"WPBS Payment - Pay ₹2500","FORM_NAME":"Franchise Form - Name","FORM_CONTACT":"Franchise Form - Contact","FORM_PLACE":"Franchise Form - Place","FORM_OCCUPATION":"Franchise Form - Occupation","MAIN_MENU":"Main Menu"};if(stage.startsWith("OPP_"))return stage.replace("OPP_","").replace("_VIEWED","");return map[stage]||stage;}
async function sendResumeForStage(phone,stage,lang){const name=getStageDisplayName(stage);if(stage==="WPBS_Q1_MSG"){await sendText(phone,`👋 *Hi! You left your WPBS enquiry incomplete.*\n\n⚠️ You have not completed *${name}* - Go back and complete your application now!\n👉 Reply *HI* to continue`);await sendButtons(phone,"Q1/3: Messages per month? - Complete now:",[{id:"wpbs_q1_l1",title:"Upto 1000"},{id:"wpbs_q1_l2",title:"1000-5000"},{id:"wpbs_q1_l3",title:"Above 5000"}]);}else if(stage==="WPBS_Q2_NUMBERS"){await sendText(phone,`👋 *Hi! You left your WPBS enquiry incomplete.*\n\n⚠️ You have not completed *${name}* - Go back and complete now!`);await sendButtons(phone,"Q2/3: How many WhatsApp Numbers? - Complete now:",[{id:"wpbs_q2_l1",title:"1 Number"},{id:"wpbs_q2_l2",title:"2 to 5"},{id:"wpbs_q2_l3",title:"More than 5"}]);}else if(stage==="WPBS_Q3_ADS"){await sendText(phone,`👋 *Hi! You left your WPBS enquiry incomplete.*\n\n⚠️ You have not completed *${name}* - Go back and complete now!`);await sendButtons(phone,"Q3/3: How many Ads? - Complete now:",[{id:"wpbs_q3_l1",title:"1 Ad"},{id:"wpbs_q3_l2",title:"2 to 5 Ads"},{id:"wpbs_q3_l3",title:"More than 5 Ads"}]);}else if(stage==="WPBS_RECOMMENDED"||stage==="WPBS_PAYMENT"){await sendPayNowUrlButton(phone,`👋 *Hi! You left your WPBS payment incomplete.*\n\n⚠️ You have not completed *Payment - Pay ₹2500* - Go back and complete now!`,WPBS_PAYMENT_LINK);await sendButtons(phone,"After payment:",[{id:"wpbs_paid",title:"I Paid - Confirm"},{id:"menu",title:"Main Menu"}]);}else{const rows=getMainMenuRows(lang);await sendText(phone,`👋 *Hi! You left your Bizmapia chat incomplete.*\n\n⚠️ You were at *${name}* - You have not completed it.\nGo back and complete your application now!\n👉 Reply *HI* to continue\n📞 ${CONTACT_NUMBER}`);setTimeout(async()=>{await sendList(phone,`You were at ${name} - Resume:`, "Resume Menu",[{title:"Menu",rows}]);},1000);}}
async function checkPendingChats(){const now=Date.now();let changed=false;for(let phone in pendingChats){const p=pendingChats[phone];const diffMin=(now-p.lastActivity)/(1000*60);const disp=getStageDisplayName(p.stage);if(!p.reminders.r1&&diffMin>=10){await sendText(phone,`🔔 *Reminder 1 - Incomplete Application*\n\n👋 Hi! You left your Bizmapia chat incomplete.\nYou were at *${disp}* - Complete in 1 min!\n👉 Reply *HI* to continue and complete *${disp}* now!\n📞 ${CONTACT_NUMBER}`);await logAllChat(phone,'AUTO_REMINDER','REMINDER_10MIN_SENT',p.lang,p.stage,`10min - ${disp}`);setTimeout(async()=>{await sendResumeForStage(phone,p.stage,p.lang);},3000);p.reminders.r1=true;changed=true;}else if(!p.reminders.r2&&diffMin>=30){await sendText(phone,`⏰ *Reminder 2 - Still Pending: ${disp}*\n\n⚠️ You have not completed *${disp}* - Go back and complete now!\n👉 Reply *HI*`);setTimeout(async()=>{await sendResumeForStage(phone,p.stage,p.lang);},2000);p.reminders.r2=true;changed=true;}else if(!p.reminders.r3&&diffMin>=1440){await sendImage(phone,ASSETS.posters.opportunity,`🔔 *Last Chance - Incomplete: ${disp}*\nYou have not completed *${disp}*\nGo back and complete now!\n👉 Reply *HI*`);setTimeout(async()=>{await sendResumeForStage(phone,p.stage,p.lang);},2000);p.reminders.r3=true;changed=true;}}for(let phone in pendingChats){if((now-pendingChats[phone].lastActivity)>72*60*60*1000&&pendingChats[phone].reminders.r3){delete pendingChats[phone];changed=true;}}if(changed)try{fs.writeFileSync("/tmp/pending_chats.json",JSON.stringify(pendingChats));}catch(e){}}
setInterval(checkPendingChats,2*60*1000);
function getOppName(id){const map={opp_1:"District Franchisee (10L-15L)",opp_2:"Corporation Franchisee (5L)",opp_3:"Municipality Franchisee (4L)",opp_4:"Business Center - Taxi (1L)",opp_5:"Business Center - Directory (1L)"};return map[id]||id;}
function getOppFeeCard(id){const cards={opp_1:`💼 *DISTRICT FRANCHISEE*\n💰 ₹10L-15L\n📍 Full District | 5Y MOU\n🏠 Rent+Salary\n📢 12M Ads\nContact: ${CONTACT_NUMBER}`,opp_2:`🏢 *CORPORATION FRANCHISEE*\n💰 ₹5L\n📍 Corporation | 3Y MOU\n🏠 Rent+Salary\n📢 12M Ads`,opp_3:`🏘️ *MUNICIPALITY FRANCHISEE*\n💰 ₹4L\n📍 Municipality | 3Y MOU\n🏠 Rent+Salary\n📢 12M Ads`,opp_4:`🚕 *BUSINESS CENTER - TAXI*\n💰 ₹1L\n📍 Area | 1Y MOU\n📢 3M Ads`,opp_5:`📖 *BUSINESS CENTER - DIRECTORY*\n💰 ₹1L\n📍 Area | 1Y MOU\n📢 3M Ads`};return cards[id]||"";}
const OPP_MAP={'OPP_1':'District Franchisee (10L-15L)','OPP_2':'Corporation Franchisee (5L)','OPP_3':'Municipality Franchisee (4L)','OPP_4':'Business Center Taxi (1L)','OPP_5':'Business Center Directory (1L)'};
function getMainMenuRows(lang){if(lang==="HI"){return[{id:"customer",title:"कस्टमर",description:"टैक्सी और सर्विस बुक करें"},{id:"driver",title:"ड्राइवर पार्टनर",description:"गाड़ी जोड़ें और कमाना शुरू करें"},{id:"business",title:"बिजनेस ओनर",description:"बिजनेस लिस्ट करें और ग्राहक पाएं"},{id:"opportunity",title:"फ्रेंचाइजी अवसर",description:"अपने क्षेत्र में फ्रेंचाइजी लें"}];}else if(lang==="ML"){return[{id:"customer",title:"കസ്റ്റമർ",description:"ടാക്സി & സർവീസ് ബുക്ക് ചെയ്യുക"},{id:"driver",title:"ഡ്രൈവർ പാർട്ണർ",description:"വാഹനം അറ്റാച്ച് ചെയ്ത് വരുമാനം"},{id:"business",title:"ബിസിനസ് ഓണർ",description:"ബിസിനസ് ലിസ്റ്റ് ചെയ്ത് കസ്റ്റമേഴ്സ്"},{id:"opportunity",title:"ഫ്രാഞ്ചൈസി അവസരം",description:"നിങ്ങളുടെ ഏരിയയിൽ ഫ്രാഞ്ചൈസി"}];}else{return[{id:"customer",title:"Customer",description:"Book a Taxi & Services"},{id:"driver",title:"Driver Partner",description:"Attach Your Vehicle & Start Earning"},{id:"business",title:"Business Owner",description:"List Your Business & Get Customers"},{id:"opportunity",title:"Franchise Opportunity",description:"Own a Franchise in Your Area"}];}}
app.get('/webhook',(req,res)=>{if(req.query['hub.verify_token']===VERIFY_TOKEN)res.send(req.query['hub.challenge']);else res.sendStatus(403);});
app.get('/',(req,res)=>res.send('V4.7 FINAL L1 L2 L3 POSTER+PAYNOW+RESTART TOGETHER + I PAID REMINDER LIVE ✅'));
app.get('/pending',(req,res)=>{res.json({total:Object.keys(pendingChats).length,pendingChats});});
app.get('/wpbs',(req,res)=>{res.json({status:"LIVE V4.7 L1:"+ASSETS.posters.wpbs_l1+" L2L3:"+ASSETS.posters.wpbs_higher,link:WPBS_PAYMENT_LINK});});
app.get('/test-sheet',async(req,res)=>{await logAllChat("919999999999","TEST","TEST_SHEET","EN","TEST_STAGE","Manual");res.send("✅ Test log sent! Check Sheet");});
app.post('/webhook',async(req,res)=>{
try{
const msg=req.body.entry?.[0]?.changes?.[0]?.value?.messages?.[0];if(!msg)return res.sendStatus(200);
if(processedIds.has(msg.id))return res.sendStatus(200);processedIds.add(msg.id);if(processedIds.size>1000)processedIds.clear();
const from=msg.from;let rawId=msg.type==="interactive"?(msg.interactive.button_reply?.id||msg.interactive.list_reply?.id||""):(msg.text?.body?.trim()||"");let input=rawId.toLowerCase();let inputUpper=rawId.toUpperCase();const rawText=msg.text?.body||"";const s=getSession(from);
await logAllChat(from,(rawText||rawId||"HI").substring(0,30),"INBOUND",s.lang,"CHAT_RECEIVED",`Raw:${rawText||rawId} stage:${s.stage}`);
if(s.stage==="FORM_NAME"){s.form.name=rawText.trim();s.stage="FORM_CONTACT";setPendingChat(from,s.lang,"FORM_CONTACT");await sendText(from,getT(s.lang,"formContact"));return res.sendStatus(200);}
if(s.stage==="FORM_CONTACT"){s.form.contact=rawText.trim();s.stage="FORM_PLACE";setPendingChat(from,s.lang,"FORM_PLACE");await sendText(from,getT(s.lang,"formPlace"));return res.sendStatus(200);}
if(s.stage==="FORM_PLACE"){s.form.place=rawText.trim();s.stage="FORM_OCCUPATION";setPendingChat(from,s.lang,"FORM_OCCUPATION");await sendList(from,getT(s.lang,"formOcc"),"Select Occupation",[{title:"Occupation",rows:[{id:"occ_running",title:"Running business"},{id:"occ_planning",title:"Planning to start"},{id:"occ_employee",title:"Employee"},{id:"occ_partner",title:"Business Partner"},{id:"occ_nri",title:"NRI"},{id:"occ_retired",title:"Retired"}]}]);return res.sendStatus(200);}
if(s.stage==="FORM_OCCUPATION"){if(input.startsWith("occ_")){const m={occ_running:"Running business",occ_planning:"Planning to start",occ_employee:"Employee",occ_partner:"Business Partner",occ_nri:"NRI",occ_retired:"Retired"};s.form.occupation=m[input]||input;}else s.form.occupation=rawText.trim();const oppFullName=OPP_MAP[s.lastOpp]||getOppName(s.lastOpp.toLowerCase())||s.lastOpp;const dateStr=new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});await appendToSheet([dateStr,from,'Franchisee_Lead',oppFullName,s.form.name,s.form.contact,s.form.place,s.form.occupation,s.lang]);await logAllChat(from,'Franchisee_Lead','COMPLETED',s.lang,'LEAD_COMPLETED',`${oppFullName} | ${s.form.name}`);clearPendingChat(from);await sendImage(from,ASSETS.posters.welcome,`${getT(s.lang,"thanksEnq")} ${s.form.name}!\n${getT(s.lang,"team24")}\nContact: ${CONTACT_NUMBER} / ${EMAIL_ID}`);s.stage="MENU";s.form={};s.lastOpp="";await new Promise(r=>setTimeout(r,2000));await sendImage(from,ASSETS.posters.franchiseBrochure,`📄 Franchise Brochure\nContact: ${CONTACT_NUMBER}\n${WEBSITE}`);await sendButtons(from,"Explore more?",[{id:"view_opp_levels",title:"View Opportunities"},{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(s.stage==="BUSINESS_DATA"){const dateStr=new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});const clean=rawText.replace(/\n/g,' | ').substring(0,200);await appendToSheet([dateStr,from,'Business_Lead',clean,clean,'','','',s.lang]);await logAllChat(from,'Business_Lead','COMPLETED',s.lang,'BUSINESS_COMPLETED',clean);clearPendingChat(from);await sendImage(from,ASSETS.posters.welcome,`✅ Business Details Received! ${getT(s.lang,"team24")}`);s.stage="MENU";s.lastOpp="";await new Promise(r=>setTimeout(r,2000));await sendImage(from,ASSETS.posters.businessBrochure,`📄 Business Listing Benefits\nContact: ${CONTACT_NUMBER}\n${WEBSITE}`);await sendButtons(from,"What next?",[{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(input==="wpbs"||input.includes("whatsapp automation")){s.stage="WPBS_Q1";s.form={};s.form.wpbs={levels:[]};setPendingChat(from,s.lang,"WPBS_Q1_MSG");await logAllChat(from,'AD_SELECTION','WPBS_Q1_START',s.lang,'WPBS_Q1','Selected WPBS');await sendText(from,`🔍 *Let's find perfect WPBS plan for you - 3 quick questions (30 sec)*\n\n*Q1/3: Messages per month?*`);await sendButtons(from,"Select:",[{id:"wpbs_q1_l1",title:"Upto 1000"},{id:"wpbs_q1_l2",title:"1000-5000"},{id:"wpbs_q1_l3",title:"Above 5000"}]);return res.sendStatus(200);}
if(s.stage==="WPBS_Q1"&&input.startsWith("wpbs_q1_")){let lvl=input.includes("_l3")?"L3":input.includes("_l2")?"L2":"L1";s.form.wpbs.q1=input;s.form.wpbs.q1_lvl=lvl;s.form.wpbs.q1_text=lvl==="L1"?"Upto 1000":lvl==="L2"?"1000-5000":"Above 5000";s.form.wpbs.levels=[lvl];s.stage="WPBS_Q2";setPendingChat(from,s.lang,"WPBS_Q2_NUMBERS");await logAllChat(from,'WPBS_Q1','ANSWERED_'+lvl,s.lang,'WPBS_Q2',`Q1:${input}=>${lvl}`);await sendText(from,`*Q2/3: How many WhatsApp Numbers / Bots?*`);await sendButtons(from,"Select:",[{id:"wpbs_q2_l1",title:"1 Number"},{id:"wpbs_q2_l2",title:"2 to 5"},{id:"wpbs_q2_l3",title:"More than 5"}]);return res.sendStatus(200);}
if(s.stage==="WPBS_Q2"&&input.startsWith("wpbs_q2_")){let lvl=input.includes("_l3")?"L3":input.includes("_l2")?"L2":"L1";s.form.wpbs.q2=input;s.form.wpbs.q2_lvl=lvl;s.form.wpbs.q2_text=lvl==="L1"?"1 Number":lvl==="L2"?"2 to 5":"More than 5";s.form.wpbs.levels.push(lvl);s.stage="WPBS_Q3";setPendingChat(from,s.lang,"WPBS_Q3_ADS");await logAllChat(from,'WPBS_Q2','ANSWERED_'+lvl,s.lang,'WPBS_Q3',`Q2:${input}=>${lvl}`);await sendText(from,`*Q3/3: How many Ads with same bot?*`);await sendButtons(from,"Select:",[{id:"wpbs_q3_l1",title:"1 Ad"},{id:"wpbs_q3_l2",title:"2 to 5 Ads"},{id:"wpbs_q3_l3",title:"More than 5 Ads"}]);return res.sendStatus(200);}
if(s.stage==="WPBS_Q3"&&input.startsWith("wpbs_q3_")){
let lvl=input.includes("_l3")?"L3":input.includes("_l2")?"L2":"L1";s.form.wpbs.q3=input;s.form.wpbs.q3_lvl=lvl;s.form.wpbs.q3_text=lvl==="L1"?"1 Ad":lvl==="L2"?"2 to 5 Ads":"More than 5 Ads";s.form.wpbs.levels.push(lvl);
let q1T=s.form.wpbs.q1_text;let q2T=s.form.wpbs.q2_text;let q3T=s.form.wpbs.q3_text;
let finalLevel="L1";let price="₹4999/-";let details="1 Number | Upto 1000 Msgs | 1 Ad";
if(s.form.wpbs.levels.includes("L2")){finalLevel="L2";price="₹9999/-";details="2-5 Numbers | 1000-5000 Msgs | 2-5 Ads";}
if(s.form.wpbs.levels.includes("L3")){finalLevel="L3";price="₹14,999/- Onwards";details="5+ Numbers | 5000+ Msgs | 5+ Ads - Full Automation+API";}
s.form.wpbs.recommended=finalLevel;s.form.wpbs.finalPrice=price;s.stage="WPBS_RECOMMENDED";setPendingChat(from,s.lang,"WPBS_RECOMMENDED");
if(finalLevel==="L1"){
await sendText(from,`✅ *Analysis Done! You BELONG to ₹4999 Plan! 🎉*\n\n📊 *Your Requirement Analysis:*\n• Msgs/Month: ${q1T} => ${s.form.wpbs.q1_lvl} ✅\n• Numbers: ${q2T} => ${s.form.wpbs.q2_lvl} ✅\n• Ads: ${q3T} => ${s.form.wpbs.q3_lvl} ✅\n\nAll 3 criteria match L1 base plan!`);
await new Promise(r=>setTimeout(r,800));
await sendImage(from,ASSETS.posters.wpbs_l1,`💎 *APPROVED - You BELONG to ₹4999 Plan!*\n📋 Includes: ${details}\n🔒 Lock Now @ ${WPBS_AMOUNT} Advance\n💳 Pay: ${WPBS_PAYMENT_LINK}\n\n✅ *APPROVED* - Starts from ₹4999/- Onwards\n📅 Deployment from DAY 8 Onwards`);
}else{
await sendText(from,`⚠️ *You are NOT belongs to our ₹4999 Base Plan (L1)*\n\n📊 *BASE PLAN L1 (₹4999) Criteria:*\n• Msgs/Month: Upto 1000 => L1\n• Numbers: 1 Number => L1\n• Ads: 1 Ad => L1\n\nOnly if ALL 3 criteria are L1, you belong to ₹4999 plan.`);
await new Promise(r=>setTimeout(r,800));
await sendText(from,`📋 *Your Submitted Requirement vs Base Plan:*\n\n*Your Requirement:*\n• Msgs/Month: ${q1T} => Belongs to *${s.form.wpbs.q1_lvl} Plan* ${s.form.wpbs.q1_lvl!="L1"?"❌ NOT L1":"✅ L1"}\n• Numbers: ${q2T} => Belongs to *${s.form.wpbs.q2_lvl} Plan* ${s.form.wpbs.q2_lvl!="L1"?"❌ NOT L1":"✅ L1"}\n• Ads: ${q3T} => Belongs to *${s.form.wpbs.q3_lvl} Plan* ${s.form.wpbs.q3_lvl!="L1"?"❌ NOT L1":"✅ L1"}\n\n*Comparison:*\n${s.form.wpbs.q1_lvl!="L1"?`• Msgs: Base L1 (Upto 1000) vs Your ${q1T} (${s.form.wpbs.q1_lvl}) - UPGRADED\n`:``}${s.form.wpbs.q2_lvl!="L1"?`• Numbers: Base L1 (1 Number) vs Your ${q2T} (${s.form.wpbs.q2_lvl}) - UPGRADED\n`:``}${s.form.wpbs.q3_lvl!="L1"?`• Ads: Base L1 (1 Ad) vs Your ${q3T} (${s.form.wpbs.q3_lvl}) - UPGRADED\n`:``}\n*Result:* Your requirement is HIGHER than base plan, so you need higher plan.`);
await new Promise(r=>setTimeout(r,800));
await sendImage(from,ASSETS.posters.wpbs_higher,`⚠️ *ATTENTION - Your requirement is HIGHER than base plan*\n\n💎 *FINAL Recommended: ${finalLevel} = ${price}*\n📋 Includes: ${details}\n💰 Total: ${price} | Advance: ${WPBS_AMOUNT}\n\n⚠️ You are NOT in ₹4999 plan because requirement is ${finalLevel}. Must pay ${price} (not ₹4999).\n\n🔄 If mistakenly chosen, restart questionnaire.\n💳 Pay Advance: ${WPBS_PAYMENT_LINK}`);
}
await new Promise(r=>setTimeout(r,1000));
// ===== V4.7 FINAL - POSTER + PAY NOW + RESTART + MAIN MENU TOGETHER - I PAID AS REMINDER AFTER 5 MIN =====
if(finalLevel==="L1"){
await sendPayNowUrlButton(from,`🔒 *Lock your ${finalLevel} plan (₹4999):*\n\n✅ *APPROVED - You BELONG to ₹4999 Plan!*\n📋 ${details}\n💰 Total: ${price} | Advance: ${WPBS_AMOUNT}\n\n🎯 Your requirement smaller? Your bill smaller too!\n📅 Deployment from DAY 8 Onwards\n\n👇 Click Pay Now to lock now:`,WPBS_PAYMENT_LINK);
await new Promise(r=>setTimeout(r,800));
await sendButtons(from,`Need to change requirement or go back?`,[{id:"wpbs_restart",title:"Restart Questionnaire"},{id:"menu",title:"Main Menu"}]);
// Schedule I Paid - Confirm as reminder after 5 minutes - FOR L1
setTimeout(async()=>{try{await sendText(from,`⏰ *Payment Reminder - ${finalLevel} Plan*\n\nDid you complete payment of ${WPBS_AMOUNT} for ${finalLevel} plan?\nIf yes, click I Paid - Confirm below so team can call you in 2 hrs.\n\nPay link if pending: ${WPBS_PAYMENT_LINK}`);await sendButtons(from,`Confirm payment:`,[{id:"wpbs_paid",title:"I Paid - Confirm"},{id:"menu",title:"Main Menu"}]);await logAllChat(from,'WPBS_REMINDER','I_PAID_REMINDER_SENT_L1',s.lang,'WPBS_PAYMENT','5min reminder L1');}catch(e){}},5*60*1000);
}else{
await sendPayNowUrlButton(from,`🔒 *Lock your ${finalLevel} plan (${price}):*\n\n⚠️ *ATTENTION - Your requirement is HIGHER than base plan (₹4999)*\n💎 FINAL: ${finalLevel} = ${price}\n📋 ${details}\n💰 Total: ${price} | Advance: ${WPBS_AMOUNT}\n\n⚠️ You are NOT in ₹4999 because requirement is ${finalLevel}. Must pay ${price} (not ₹4999).\n🔄 If mistakenly chosen, restart questionnaire.\n\n👇 Click Pay Now to lock now (Balance after demo):`,WPBS_PAYMENT_LINK);
await new Promise(r=>setTimeout(r,800));
await sendButtons(from,`Need to change requirement?`,[{id:"wpbs_restart",title:"Restart Questionnaire"},{id:"menu",title:"Main Menu"}]);
// Schedule I Paid - Confirm as reminder after 5 minutes - FOR L2 L3
setTimeout(async()=>{try{await sendText(from,`⏰ *Payment Reminder - ${finalLevel} Plan (${price})*\n\nDid you complete payment of ${WPBS_AMOUNT} for ${finalLevel} plan?\nYour plan: ${finalLevel} = ${price} (NOT ₹4999)\nIf paid, click I Paid - Confirm so team can call you in 2 hrs.\n\nPay link if pending: ${WPBS_PAYMENT_LINK}`);await sendButtons(from,`Confirm payment:`,[{id:"wpbs_paid",title:"I Paid - Confirm"},{id:"wpbs_restart",title:"Restart Questionnaire"},{id:"menu",title:"Main Menu"}]);await logAllChat(from,'WPBS_REMINDER','I_PAID_REMINDER_SENT_'+finalLevel,s.lang,'WPBS_PAYMENT','5min reminder '+finalLevel);}catch(e){}},5*60*1000);
}
await logAllChat(from,'WPBS_SORTED',finalLevel,s.lang,'WPBS_RECOMMENDED',`Q1:${s.form.wpbs.q1_lvl}(${q1T}) Q2:${s.form.wpbs.q2_lvl}(${q2T}) Q3:${s.form.wpbs.q3_lvl}(${q3T}) => ${finalLevel}`);
return res.sendStatus(200);}
if(input==="wpbs_restart"){s.stage="WPBS_Q1";s.form={};s.form.wpbs={levels:[]};setPendingChat(from,s.lang,"WPBS_Q1_MSG");await logAllChat(from,'WPBS','RESTARTED',s.lang,'WPBS_Q1','Restarted');await sendText(from,`🔄 *Restarting Questionnaire - Fill again correctly*\n\n*Q1/3: Messages per month?*`);await sendButtons(from,"Select:",[{id:"wpbs_q1_l1",title:"Upto 1000"},{id:"wpbs_q1_l2",title:"1000-5000"},{id:"wpbs_q1_l3",title:"Above 5000"}]);return res.sendStatus(200);}
if(input.startsWith("wpbs_pay_")){let lvl=input.split("_").pop().toUpperCase();setPendingChat(from,s.lang,"WPBS_PAYMENT");await logAllChat(from,'WPBS','PAYMENT_LINK_SENT_'+lvl,s.lang,'WPBS_PAYMENT',WPBS_PAYMENT_LINK);await sendPayNowUrlButton(from,`💳 *Pay ${WPBS_AMOUNT} Advance to Lock ${lvl}*\n\n🔒 *Lock Your WPBS Plan (${lvl}):*`,WPBS_PAYMENT_LINK);await sendButtons(from,"After payment click:",[{id:"wpbs_paid",title:"I Paid - Confirm"},{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(input==="wpbs_paid"){let lvl=s.form?.wpbs?.recommended||"L1";let total=lvl==="L1"?4999:lvl==="L2"?9999:14999;let balance=total-2500;const dateStr=new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});const q1=s.form?.wpbs?.q1_lvl||"L1";const q2=s.form?.wpbs?.q2_lvl||"L1";const q3=s.form?.wpbs?.q3_lvl||"L1";const q1T=s.form?.wpbs?.q1_text||"";const q2T=s.form?.wpbs?.q2_text||"";const q3T=s.form?.wpbs?.q3_text||"";await appendToSheet([dateStr,from,'WPBS_Lead',`WPBS ${lvl} - Advance 2500 - Q1:${q1}(${q1T}) Q2:${q2}(${q2T}) Q3:${q3}(${q3T}) => ${lvl} | Total ${total}`,from,from,'',`PAID_${lvl}`,s.lang]);await logAllChat(from,'WPBS_Lead','PAID_CONFIRMED_'+lvl,s.lang,'WPBS_PAID',`Advance 2500 Paid | ${lvl} | Q1:${q1} Q2:${q2} Q3:${q3} | Balance ${balance}`);clearPendingChat(from);await sendText(from,`🎉 *Thank you for locking WPBS ${lvl} Plan! ✅*\n\n✅ Payment of ${WPBS_AMOUNT} Advance received\n📊 Your Final Plan: *${lvl}*\n💰 Total: ₹${total} | Paid: ₹2500 | Balance: ₹${balance} payable after demo\n\n📊 Your Requirement:\n• Msgs: ${q1T} (${q1})\n• Numbers: ${q2T} (${q2})\n• Ads: ${q3T} (${q3})\n\n📞 *Next Step:* Team calls you in 2 hrs on *${CONTACT_NUMBER}*\n🚀 Deployment from *DAY 8* Onwards`);s.stage="COMPLETED_WPBS";return res.sendStatus(200);}
const VALID_IDS=['lang_en','lang_hi','lang_ml','english','hindi','malayalam','customer','driver','business','opportunity','view_opp_levels','opp_search','franchise_opportunity','opp_1','opp_2','opp_3','opp_4','opp_5','opp_yes','opp_no','activate','driver_benefit','driver_claim','business_list','menu','occ_running','occ_planning','occ_employee','occ_partner','occ_nri','occ_retired','wpbs','wpbs_paid','wpbs_q1_l1','wpbs_q1_l2','wpbs_q1_l3','wpbs_q2_l1','wpbs_q2_l2','wpbs_q2_l3','wpbs_q3_l1','wpbs_q3_l2','wpbs_q3_l3','wpbs_pay_l1','wpbs_pay_l2','wpbs_pay_l3','wpbs_restart','hi','hello','hey','hlo','start','hai'];
const isInteractive=msg.type==="interactive";const isValid=VALID_IDS.some(v=>input===v||input.includes(v)||inputUpper===v.toUpperCase())||isInteractive;
if(!isValid&&!["FORM_NAME","FORM_CONTACT","FORM_PLACE","FORM_OCCUPATION","BUSINESS_DATA","AD_SELECTION","WPBS_Q1","WPBS_Q2","WPBS_Q3","WPBS_RECOMMENDED","WPBS_PAYMENT"].includes(s.stage)){await logAllChat(from,'CATCH_ALL','INVALID_INPUT',s.lang,'WELCOME_SENT',`Invalid: ${rawText||rawId}`);s.stage="LANG";setPendingChat(from,s.lang,"LANG_SELECTION");await sendWelcomeTextAndLanguage(from);return res.sendStatus(200);}
if(s.stage==="NEW"||["hi","hello","hey","hlo","start","hai"].includes(input)){s.stage="LANG";s.form={};s.lastOpp="";setPendingChat(from,s.lang,"LANG_SELECTION");await logAllChat(from,'CHAT_STARTED','NEW_USER_HI',s.lang,'LANG_SELECTION','User said HI');await sendImage(from,ASSETS.posters.welcome,"👋 Welcome to Bizmapia! Your Success, Our Platform 🙏\n\nThank you for reaching out!");await new Promise(r=>setTimeout(r,800));await sendButtons(from,"Select language / भाषा चुनें / ഭാഷ തിരഞ്ഞെടുക്കുക",[{id:"lang_en",title:"English"},{id:"lang_hi",title:"Hindi"},{id:"lang_ml",title:"Malayalam"}]);return res.sendStatus(200);}
if(s.stage==="LANG"||input.startsWith("lang_")){if(input.includes("en"))s.lang="EN";else if(input.includes("hi"))s.lang="HI";else if(input.includes("ml"))s.lang="ML";s.stage="AD_SELECTION";setPendingChat(from,s.lang,"AD_SELECTION");await logAllChat(from,'LANGUAGE_SELECTED','ACTIVE',s.lang,'AD_SELECTION',`Selected ${s.lang}`);const caption=`🎯 *SELECT YOUR OPTION FROM POSTERS*\n\nYou saw our ad! Which opportunity are you interested in?\n\n*Left - WHATSAPP AUTOMATION (WPBS):*\n✅ Low-cost Business Automation\n💰 Starts from ₹4999/- Onwards\n🚀 Deployment from Day 8\n📞 ${CONTACT_NUMBER}\n\n*Right - BUSINESS OPPORTUNITY:*\n✅ 4 Opportunities Under One Brand\n✅ 50+ Franchisees Allotted in Kerala\n💰 1L to 15L Investment\n\n👇 *Please select your option below:*`;await sendImage(from,ASSETS.posters.selectOption,caption);await new Promise(r=>setTimeout(r,1000));await sendButtons(from,"Select your option:",[{id:"wpbs",title:"WhatsApp Automation"},{id:"opportunity",title:"Business Opportunity"}]);return res.sendStatus(200);}
if(input==="customer"){setPendingChat(from,s.lang,"CUSTOMER_VIEWED");await logAllChat(from,'MENU_CLICK','CUSTOMER',s.lang,'CUSTOMER_VIEWED','Clicked Customer');await sendImage(from,ASSETS.posters.customer,`${getT(s.lang,"customerH")}\n✅ Taxi ✅ Delivery ✅ Business Offers\nContact: ${CONTACT_NUMBER}`);await new Promise(r=>setTimeout(r,800));await sendText(from,`📲 *Download Customer App:*\n${ASSETS.apps.customer}`);await sendButtons(from,getT(s.lang,"whatToKnow"),[{id:"activate",title:"Claim Now"},{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(input==="activate"){clearPendingChat(from);await logAllChat(from,'CUSTOMER','APP_DOWNLOAD',s.lang,'ACTIVATE','Customer app');await sendText(from,`✅ *Offer Activated!*\nOpen app:\n📲 ${ASSETS.apps.customer}`);return res.sendStatus(200);}
if(input==="driver"){setPendingChat(from,s.lang,"DRIVER_VIEWED");await logAllChat(from,'MENU_CLICK','DRIVER',s.lang,'DRIVER_VIEWED','Clicked Driver');await sendImage(from,ASSETS.posters.driver,`${getT(s.lang,"driverH")}\nAuto Rs.33 / Car Rs.49\nContact: ${CONTACT_NUMBER}`);await new Promise(r=>setTimeout(r,800));await sendText(from,`📲 Download Driver App:\n${ASSETS.apps.driver}`);await sendButtons(from,"Claim your free recharge:",[{id:"driver_benefit",title:"Free Recharge"},{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(input==="driver_benefit"){setPendingChat(from,s.lang,"DRIVER_BENEFIT");await logAllChat(from,'DRIVER','BENEFIT_VIEWED',s.lang,'DRIVER_BENEFIT','Viewed free recharge');await sendImage(from,ASSETS.posters.freeRecharge,"🎉 *FREE Recharge Benefit!*\n33 Rs Recharge = 24hr Unlimited Trips");await new Promise(r=>setTimeout(r,800));await sendText(from,`📲 Get FREE Recharge:\n${ASSETS.apps.driver}`);await sendButtons(from,"Claim:",[{id:"driver_claim",title:"Claim Now"},{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(input==="driver_claim"){clearPendingChat(from);await logAllChat(from,'DRIVER','CLAIMED',s.lang,'DRIVER_CLAIM','Free recharge claimed');await sendText(from,`✅ *Your free recharge going to activate*\n📲 ${ASSETS.apps.driver}`);addReminder(from,"Driver_FreeRecharge");s.stage="MENU";return res.sendStatus(200);}
if(input==="business"){setPendingChat(from,s.lang,"BUSINESS_VIEWED");await logAllChat(from,'MENU_CLICK','BUSINESS',s.lang,'BUSINESS_VIEWED','Clicked Business');await sendImage(from,ASSETS.posters.business,`${getT(s.lang,"businessH")}\nGet More Local Visibility`);await new Promise(r=>setTimeout(r,800));await sendButtons(from,"Register your business",[{id:"business_list",title:"How to List"},{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(input==="business_list"){setPendingChat(from,s.lang,"BUSINESS_FORM_PENDING");await logAllChat(from,'BUSINESS','FORM_STARTED',s.lang,'BUSINESS_FORM_PENDING','Started business form');await sendImage(from,ASSETS.posters.businessBenefit,"🎉 *Benefit 1 Year Subscription and Get Discount*");await new Promise(r=>setTimeout(r,1000));await sendText(from,"📝 *Send business details in ONE message:*\n\nShop Name:\nMobile:\nCategory:\nLocation:");s.stage="BUSINESS_DATA";s.lastOpp="Business";return res.sendStatus(200);}
if(["opportunity","opportunities_franchise","view_opp_levels","opp_search","franchise_opportunity"].includes(input)){setPendingChat(from,s.lang,"FRANCHISE_OPPORTUNITY_VIEWED");await logAllChat(from,'MENU_CLICK','FRANCHISE',s.lang,'FRANCHISE_OPPORTUNITY','Clicked Business Opportunity');await sendImage(from,ASSETS.posters.opportunity,`${getT(s.lang,"oppH")}\n${getT(s.lang,"oppSub")}\nContact: ${CONTACT_NUMBER} | ${EMAIL_ID}`);await new Promise(r=>setTimeout(r,800));await sendText(from,`🎥 Watch About Bizmapia:\n${ASSETS.videos.main_opp}`);await new Promise(r=>setTimeout(r,800));await sendList(from,`💰 Select Franchise Level:\nDistrict 10L-15L (5Y, 12M Ads)\nMuni/Corp 4L-5L (3Y, 12M Ads)\nBusiness Center 1L (1Y, 3M Ads)`,"View Opportunities",[{title:"All Franchise Opportunities",rows:[{id:"opp_1",title:"District Franchisee",description:"💰 10L-15L | 5Y | 12M Ads"},{id:"opp_2",title:"Corporation Franchisee",description:"💰 5L | 3Y | 12M Ads"},{id:"opp_3",title:"Municipality Franchisee",description:"💰 4L | 3Y | 12M Ads"},{id:"opp_4",title:"Business Center - Taxi",description:"💰 1L | 1Y | 3M Ads"},{id:"opp_5",title:"Business Center - Directory",description:"💰 1L | 1Y | 3M Ads"}]}]);await new Promise(r=>setTimeout(r,1200));await sendButtons(from,"👇 If list not visible:",[{id:"opp_1",title:"District (10L-15L)"},{id:"opp_2",title:"Corporation (5L)"},{id:"opp_3",title:"Municipality (4L)"}]);await new Promise(r=>setTimeout(r,800));await sendButtons(from,"More:",[{id:"opp_4",title:"Taxi Center (1L)"},{id:"opp_5",title:"Directory (1L)"},{id:"menu",title:"Main Menu"}]);return res.sendStatus(200);}
if(["opp_1","opp_2","opp_3","opp_4","opp_5"].includes(input)){s.lastOpp=inputUpper;setPendingChat(from,s.lang,`OPP_${input}_VIEWED`);await logAllChat(from,'FRANCHISE_LEVEL','VIEWED',s.lang,`OPP_${input}_VIEWED`,getOppName(input));await sendImage(from,ASSETS.posters.opportunity,`💼 *${getOppName(input)}*`);await new Promise(r=>setTimeout(r,800));await sendText(from,getOppFeeCard(input));await new Promise(r=>setTimeout(r,800));await sendText(from,`🎥 Watch full awareness:\n${ASSETS.videos[input]}\nContact: ${CONTACT_NUMBER}`);if(oppTimers[from])clearTimeout(oppTimers[from]);oppTimers[from]=setTimeout(async()=>{await sendButtons(from,`⏰ ${getT(s.lang,"yesNoQ")}`,[{id:"opp_yes",title:"Yes"},{id:"opp_no",title:"No"},{id:"opp_search",title:"Search Other"}]);},5*60*1000);await new Promise(r=>setTimeout(r,800));await sendButtons(from,getT(s.lang,"yesNoQ"),[{id:"opp_yes",title:"Yes"},{id:"opp_no",title:"No"},{id:"opp_search",title:"Search Other"}]);return res.sendStatus(200);}
if(input==="opp_yes"){if(oppTimers[from])clearTimeout(oppTimers[from]);s.stage="FORM_NAME";s.form={};setPendingChat(from,s.lang,"FORM_NAME");await logAllChat(from,'FRANCHISE','YES_CLICKED',s.lang,'FORM_NAME',`Said YES to ${s.lastOpp}`);await sendText(from,getT(s.lang,"formName"));return res.sendStatus(200);}
if(input==="opp_no"){if(oppTimers[from])clearTimeout(oppTimers[from]);clearPendingChat(from);await logAllChat(from,'FRANCHISE','NO_OPTED_OUT',s.lang,'OPTED_OUT',`Said NO to ${s.lastOpp}`);await sendText(from,`You are opted out 🙏\nType *HI* to start again.\nContact: ${CONTACT_NUMBER}`);s.stage="NEW";return res.sendStatus(200);}
if(input==="menu"||input==="view_opp_levels"){s.stage="MENU";setPendingChat(from,s.lang,"MAIN_MENU");await logAllChat(from,'MENU','MAIN_MENU',s.lang,'MAIN_MENU','Back to main menu');await sendList(from,getT(s.lang,"whatToKnow"),"Main Menu",[{title:"Menu",rows:getMainMenuRows(s.lang)}]);return res.sendStatus(200);}
if(s.stage==="MENU"){setPendingChat(from,s.lang,"MAIN_MENU");await sendList(from,getT(s.lang,"selectMenu"),"Main Menu",[{title:"Menu",rows:getMainMenuRows(s.lang)}]);return res.sendStatus(200);}
await sendText(from,getT(s.lang,"hiAgain"));res.sendStatus(200);}catch(err){console.log(err);res.sendStatus(200);}});
app.post('/razorpay-webhook',(req,res)=>{console.log("Razorpay:",req.body.event);res.status(200).send("OK");});
app.listen(PORT,()=>console.log(`V4.7 FINAL POSTER+PAYNOW+RESTART L1:${ASSETS.posters.wpbs_l1} L2L3:${ASSETS.posters.wpbs_higher} Running on ${PORT}`));
